#ifndef __FCNTL_H
#define __FCNTL_H
/*
 *  arch/i386/fcntl.h
 *
 * =========================================================================
 *
 *                          Open Watcom Project
 *
 * Copyright (c) 2004-2025 The Open Watcom Contributors. All Rights Reserved.
 *
 *    This file is automatically generated. Do not edit directly.
 *
 * =========================================================================
 */

/*
 *  File status flags used for open() and fcntl().
 */
#define O_NONBLOCK  004000  /*  Non-blocking I/O                */

/*
 *  fcntl() requests
 */
#define F_DUPFD     0       /* Duplicate file descriptor   */
#define F_GETFD     1       /* Get file descriptor flags   */
#define F_SETFD     2       /* Set file descriptor flags   */
#define F_GETFL     3       /* Get file status flags   */
#define F_SETFL     4       /* Set file status flags   */
#define F_GETLK     5       /* Get record locking info.  */
#define F_SETLK     6       /* Set record locking info (non-blocking). */
#define F_SETLKW    7       /* Set record locking info (blocking) */
#define F_GETLK64   12      /* Get record locking info.  */
#define F_SETLK64   13      /* Set record locking info (non-blocking).  */
#define F_SETLKW64  14      /* Set record locking info (blocking).  */

_WCRTLINK extern int        fcntl( int __fildes, int __cmd, ... );

/*
 *  File descriptor flags used for fcntl()
 */
#define FD_CLOEXEC  0x01    /*  Close on exec       */

#endif
